ROUTE_MAP = {
    1: "Interstate",
    2: "US Highway",
    3: "State Highway",
    4: "County Road",
    5: "Local Township",
    6: "Municipal Street",
    7: "Frontage Road",
    8: "Other",
    9: "Unknown",
    10: "Parkway",
    11: "Off-Interstate Business",
    12: "Secondary Route",
    13: "Bureaue of Indian Affairs",
    95: "Other"
}

DISPLAY_NAME_MAP = {
    "Athens-Clarke County unified government (balance)": "Athens",
    "Augusta-Richmond County consolidated government (balance)": "Augusta",
    "Louisville/Jefferson County metro government (balance)": "Louisville",
    "Lexington-Fayette urban county": "Lexington",
    "Nashville-Davidson metropolitan government (balance)": "Nashville",
    "Macon-Bibb County": "Macon",
    "Urban Honolulu": "Honolulu",
    "Indianapolis city (balance)": "Indianapolis",
    "Boise City": "Boise",
    "Milford City (balance)": "Milford City",
}

STATE_FIPS_MAP = {
   "01": "Alabama",
   "02": "Alaska",
   "04": "Arizona",
   "05": "Arkansas",
   "06": "California",
   "08": "Colorado",
   "09": "Connecticut",
   "10": "Delaware",
   "11": "District of Columbia",
   "12": "Florida",
   "13": "Georgia",
   "15": "Hawaii",
   "16": "Idaho",
   "17": "Illinois",
   "18": "Indiana",
   "19": "Iowa",
   "20": "Kansas",
   "21": "Kentucky",
   "22": "Louisiana",
   "23": "Maine",
   "24": "Maryland",
   "25": "Massachusetts",
   "26": "Michigan",
   "27": "Minnesota",
   "28": "Mississippi",
   "29": "Missouri",
   "30": "Montana",
   "31": "Nebraska",
   "32": "Nevada",
   "33": "New Hampshire",
   "34": "New Jersey",
   "35": "New Mexico",
   "36": "New York",
   "37": "North Carolina",
   "38": "North Dakota",
   "39": "Ohio",
   "40": "Oklahoma",
   "41": "Oregon",
   "42": "Pennsylvania",
   "44": "Rhode Island",
   "45": "South Carolina",
   "46": "South Dakota",
   "47": "Tennessee",
   "48": "Texas",
   "49": "Utah",
   "50": "Vermont",
   "51": "Virginia",
   "53": "Washington",
   "54": "West Virginia",
   "55": "Wisconsin",
   "56": "Wyoming"
}

PLACE_NAME_MAP = {
    ("Saint Louis", "Missouri"): "St. Louis",
    ("St Louis", "Missour"): "St. Louis",
    ("Ft Myers", "Florida"): "Fort Myers",
    ("Saint Petersburg", "Florida"): "St. Petersburg",
    ("St Petersburg", "Florida"): "St. Petersburg",
    ("Port Saint Lucie", "Florida"): "Port St. Lucie",
    ("Louisville", "Kentucky"): "Louisville/Jefferson County metro government (balance)",
    ("Lexington", "Kentucky"): "Lexington-Fayette urban county",
    ("Nashville", "Tennessee"): "Nashville-Davidson metropolitan government (balance)",
    ("Athens", "Georgia"): "Athens-Clarke County unified government (balance)",
    ("Augusta", "Georgia"): "Augusta-Richmond County consolidated government (balance)",
    ("Macon", "Georgia"): "Macon-Bibb County",
    ("Ventura", "California"): "San Buenaventura (Ventura)",
    ("Colorado Spgs", "Colorado"): "Colorado Springs",
    ("Washington, DC", "District of Columbia"): "Washington",
    ("Honolulu", "Hawaii"): "Urban Honolulu",
    ("Boise", "Idaho"): "Boise City",
    ("Indianapolis", "Indiana"): "Indianapolis city (balance)",
    ("Edison", "New Jersey"): "Other",
    ("Hamilton Township", "New Jersey"): "Other",
    ("Middle Village", "New York"): "New York",
    ("New York City", "New York"): "New York",
    ("New York -Bronx", "New York"): "New York",
    ("New York -Queens", "New York"): "New York",
    ("New York New York", "New York"): "New York",
    ("New York -Kings", "New York"): "New York",
    ("Winston Salem", "North Carolina"): "Winston-Salem",
}